spring:
  ## mysql数据库连接信息配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.55.116:3306/lucky_organization?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: lucky1212
  redis:
    host: 192.168.0.60
    port: 6379

eureka:
  instance:
    ## 注册到eurekaip地址
    hostname: 47.100.55.116
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:18000/eureka/



